; lumary-zigbee/platformio.ini
[env:esp32h2]
platform = espressif32
board = esp32h2
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DZIGBEE_MODE_ED
