; lumary-zigbee/platformio.ini
[env:esp32h2]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip
board = esp32h2
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DZIGBEE_MODE_ED
