#!/usr/bin/env python3
"""Builds a standalone single-file copy of the ring designer.

tools/designer/index.html is ES modules across four files, which is the right
shape to develop and test but means it has to be served. This flattens the
modules into the page so the result is one .html you can open from disk, mail
to someone, or host anywhere.

Generated, never hand-edited: the point is that the standalone copy cannot
drift from the modules the tests actually cover.

The modules are concatenated into a single scope, so a top-level name defined
by two of them would silently shadow. This checks for that and fails rather
than emitting a page that is subtly broken -- which is how `recipe` (the
editor's working copy) and `recipe()` (the preset helper, now makeRecipe) were
caught.

Usage:  python scripts/build-designer-single.py [output.html]
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "tools" / "designer"

# Dependency order: gamma is imported by recipe, recipe by presets.
MODULES = ["gamma.mjs", "recipe.mjs", "presets.mjs"]

IMPORT_RE = re.compile(r"^\s*import\s[^;]*?;\s*$", re.M | re.S)
EXPORT_RE = re.compile(r"^export\s+(?=const|let|var|function|class)", re.M)
TOPLEVEL_RE = re.compile(r"^(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)", re.M)


def strip_module(text):
    """Removes import statements and the `export` keyword, leaving plain code."""
    return EXPORT_RE.sub("", IMPORT_RE.sub("", text)).strip()


def main():
    out_path = (
        pathlib.Path(sys.argv[1])
        if len(sys.argv) > 1
        else ROOT / "build" / "lumary-ring-designer.html"
    )

    page = (SRC / "index.html").read_text()

    chunks = []
    owners = {}
    for name in MODULES:
        body = strip_module((SRC / name).read_text())
        for symbol in TOPLEVEL_RE.findall(body):
            if symbol in owners:
                raise SystemExit(
                    f"name collision: '{symbol}' is defined in both "
                    f"{owners[symbol]} and {name}. The standalone build shares one "
                    f"scope, so rename one of them."
                )
            owners[symbol] = name
        chunks.append(f"// ── inlined from {name} " + "─" * (56 - len(name)) + f"\n{body}")

    # The page's own module script is the last chunk, with its imports dropped.
    match = re.search(r'<script type="module">(.*?)</script>', page, re.S)
    if match is None:
        raise SystemExit("could not find the page's module script in index.html")

    page_script = strip_module(match.group(1))
    for symbol in TOPLEVEL_RE.findall(page_script):
        if symbol in owners:
            raise SystemExit(
                f"name collision: '{symbol}' is defined in both {owners[symbol]} "
                f"and index.html. The standalone build shares one scope, so rename one."
            )

    chunks.append("// ── inlined from index.html " + "─" * 46 + f"\n{page_script}")

    banner = (
        "// GENERATED by scripts/build-designer-single.py -- do not edit.\n"
        "// Source of truth is tools/designer/, which is what the tests cover.\n"
    )
    bundled = '<script type="module">\n' + banner + "\n\n".join(chunks) + "\n</script>"
    page = page[: match.start()] + bundled + page[match.end():]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(page)
    kb = len(page) / 1024
    print(f"wrote {out_path} ({kb:.0f} KB, {len(owners)} symbols inlined)")


if __name__ == "__main__":
    main()
