#pragma once
#include <stdint.h>
#include "color.h"

// Perceptual brightness correction for both light sources.
//
// Home Assistant's brightness slider is perceptually linear; LED output is
// linear in drive value. Without a curve between them the bottom third of the
// slider does very little and then jumps.
//
// The curve is the CIE 1931 lightness function, not a power law:
//
//     L* = brightness / 255 * 100
//     Y  = L* / 903.3            for L* <= 8      <- linear segment
//     Y  = ((L* + 16) / 116)^3   for L* > 8
//
// That linear segment is why this reaches brightness 1 at all. With gamma 2.2
// every input below 15 rounds to zero at 8-bit output -- a naive gamma LUT
// would have made the low end worse than the linear scaling it replaced.
//
// Apply this to the BRIGHTNESS SCALAR, never to individual output channels:
// gamma(a * b) != gamma(a) * b, so a per-channel curve distorts every ratio
// between channels. On the white string that ratio is the colour temperature
// (a 2.98:1 mix becomes 10.83:1, so the fixture drifts warm as it dims); on the
// ring it shifts the hue of any mixed colour.
//
// Tables are generated by scripts/gen-gamma-tables.py and verified entry by
// entry against the formula in test/test_brightness. They are checked in
// because the ESP32-H2 is RISC-V with no FPU (pow() is soft-float) and because
// std::pow is not constexpr in C++17.
//
// `static const` rather than `inline constexpr`: the Arduino ESP32 toolchain's
// default C++ standard varies by framework version, and only effects.cpp
// includes this, so the 768 bytes exist once.

// --- gamma8 table begin ---   (ring: 8-bit in -> 8-bit out)
static const uint8_t kGamma8[256] = {
      0,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   2,
      2,   2,   2,   2,   2,   2,   2,   3,   3,   3,   3,   3,   3,   3,   3,   4,
      4,   4,   4,   4,   4,   5,   5,   5,   5,   5,   6,   6,   6,   6,   6,   7,
      7,   7,   7,   8,   8,   8,   8,   9,   9,   9,  10,  10,  10,  10,  11,  11,
     11,  12,  12,  12,  13,  13,  13,  14,  14,  15,  15,  15,  16,  16,  17,  17,
     17,  18,  18,  19,  19,  20,  20,  21,  21,  22,  22,  23,  23,  24,  24,  25,
     25,  26,  26,  27,  28,  28,  29,  29,  30,  31,  31,  32,  32,  33,  34,  34,
     35,  36,  37,  37,  38,  39,  39,  40,  41,  42,  43,  43,  44,  45,  46,  47,
     47,  48,  49,  50,  51,  52,  53,  54,  54,  55,  56,  57,  58,  59,  60,  61,
     62,  63,  64,  65,  66,  67,  68,  70,  71,  72,  73,  74,  75,  76,  77,  79,
     80,  81,  82,  83,  85,  86,  87,  88,  90,  91,  92,  94,  95,  96,  98,  99,
    100, 102, 103, 105, 106, 108, 109, 110, 112, 113, 115, 116, 118, 120, 121, 123,
    124, 126, 128, 129, 131, 132, 134, 136, 138, 139, 141, 143, 145, 146, 148, 150,
    152, 154, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
    183, 185, 187, 189, 191, 193, 196, 198, 200, 202, 204, 207, 209, 211, 214, 216,
    218, 220, 223, 225, 228, 230, 232, 235, 237, 240, 242, 245, 247, 250, 252, 255,
};
// --- gamma8 table end ---

// --- gamma12 table begin ---   (white string: 8-bit in -> 12-bit out)
static const uint16_t kGamma12[256] = {
       0,    2,    4,    5,    7,    9,   11,   12,   14,   16,   18,   20,
      21,   23,   25,   27,   28,   30,   32,   34,   36,   37,   39,   41,
      43,   45,   47,   49,   52,   54,   56,   59,   61,   64,   66,   69,
      72,   75,   77,   80,   83,   87,   90,   93,   96,  100,  103,  107,
     111,  115,  118,  122,  126,  131,  135,  139,  144,  148,  153,  157,
     162,  167,  172,  177,  182,  187,  193,  198,  204,  209,  215,  221,
     227,  233,  239,  246,  252,  259,  265,  272,  279,  286,  293,  300,
     308,  315,  323,  330,  338,  346,  354,  362,  371,  379,  388,  396,
     405,  414,  423,  432,  442,  451,  461,  470,  480,  490,  501,  511,
     521,  532,  543,  553,  564,  576,  587,  598,  610,  622,  634,  646,
     658,  670,  683,  695,  708,  721,  734,  748,  761,  775,  788,  802,
     816,  831,  845,  860,  874,  889,  904,  920,  935,  951,  966,  982,
     999, 1015, 1031, 1048, 1065, 1082, 1099, 1116, 1134, 1152, 1170, 1188,
    1206, 1224, 1243, 1262, 1281, 1300, 1320, 1339, 1359, 1379, 1399, 1420,
    1440, 1461, 1482, 1503, 1525, 1546, 1568, 1590, 1612, 1635, 1657, 1680,
    1703, 1726, 1750, 1774, 1797, 1822, 1846, 1870, 1895, 1920, 1945, 1971,
    1996, 2022, 2048, 2074, 2101, 2128, 2155, 2182, 2209, 2237, 2265, 2293,
    2321, 2350, 2378, 2407, 2437, 2466, 2496, 2526, 2556, 2587, 2617, 2648,
    2679, 2711, 2743, 2774, 2807, 2839, 2872, 2905, 2938, 2971, 3005, 3039,
    3073, 3107, 3142, 3177, 3212, 3248, 3283, 3319, 3356, 3392, 3429, 3466,
    3503, 3541, 3578, 3617, 3655, 3694, 3732, 3772, 3811, 3851, 3891, 3931,
    3972, 4012, 4054, 4095,
};
// --- gamma12 table end ---

inline uint8_t gamma8(uint8_t brightness) {
    return kGamma8[brightness];
}

inline uint16_t gamma12(uint8_t brightness) {
    return kGamma12[brightness];
}

// Curve the brightness, then scale the colour by it linearly, so the pixel's
// hue and saturation survive dimming unchanged.
inline CRGB scale_brightness_gamma(CRGB c, uint8_t brightness) {
    return scale_brightness(c, gamma8(brightness));
}

// 12-bit duties for the inner white string's two channels.
struct WhiteMix {
    uint16_t ww;   // 2700 K
    uint16_t cw;   // 6500 K
};

// Curve the level once, then split it linearly between the two strings, which
// is what keeps colour temperature constant as the fixture dims.
//
// `cct`: 0 = fully warm, 255 = fully cool. The two coefficients sum to 255, so
// total output is constant across colour temperature.
//
// Divides by 255 rather than using scale8's `>> 8`: the shift maps a full 255
// mix to 254/255 of the total, so pure warm would never quite reach full duty.
// Same off-by-one that scale_level() in light_state.h works around.
inline WhiteMix white_mix_gamma(uint8_t level, uint8_t cct) {
    const uint32_t total = gamma12(level);
    return {
        uint16_t(total * (255u - cct) / 255u),
        uint16_t(total * cct / 255u),
    };
}
