// Native (host) tests for the perceptual brightness curve.
// Run: scripts\run-native-tests.bat
#include <unity.h>
#include <math.h>      // lround, pow
#include <stdlib.h>    // labs
#include "brightness.h"

void setUp(void) {}
void tearDown(void) {}

// The reference implementation, recomputed here in double. The tables in
// brightness.h are generated by scripts/gen-gamma-tables.py; this is what stops
// them drifting from the formula they claim to encode.
static uint32_t cie_reference(uint8_t brightness, uint32_t out_max) {
    if (brightness == 0) return 0;
    const double lightness = brightness / 255.0 * 100.0;
    const double luminance = (lightness <= 8.0)
        ? lightness / 903.3
        : pow((lightness + 16.0) / 116.0, 3.0);
    const uint32_t v = (uint32_t)lround(out_max * luminance);
    return v == 0 ? 1 : v;
}

// ── the tables match the formula ──────────────────────────────────────────

void test_gamma8_matches_the_formula(void) {
    for (int i = 0; i < 256; i++) {
        TEST_ASSERT_EQUAL_UINT32(cie_reference((uint8_t)i, 255), gamma8((uint8_t)i));
    }
}

void test_gamma12_matches_the_formula(void) {
    for (int i = 0; i < 256; i++) {
        TEST_ASSERT_EQUAL_UINT32(cie_reference((uint8_t)i, 4095), gamma12((uint8_t)i));
    }
}

// ── curve shape ───────────────────────────────────────────────────────────

void test_both_curves_are_monotonic(void) {
    for (int i = 0; i < 255; i++) {
        TEST_ASSERT_TRUE(gamma8((uint8_t)i)  <= gamma8((uint8_t)(i + 1)));
        TEST_ASSERT_TRUE(gamma12((uint8_t)i) <= gamma12((uint8_t)(i + 1)));
    }
}

void test_endpoints_are_exact(void) {
    TEST_ASSERT_EQUAL_UINT8(0,     gamma8(0));
    TEST_ASSERT_EQUAL_UINT8(255,   gamma8(255));
    TEST_ASSERT_EQUAL_UINT16(0,    gamma12(0));
    TEST_ASSERT_EQUAL_UINT16(4095, gamma12(255));
}

// This is the regression test for the bug the whole change exists to fix:
// linear scaling left the bottom of the slider doing nothing, and a naive
// gamma LUT on 8-bit output would have made brightness 1..14 go fully dark.
void test_no_nonzero_brightness_goes_dark(void) {
    for (int i = 1; i < 256; i++) {
        TEST_ASSERT_GREATER_THAN_UINT8(0,  gamma8((uint8_t)i));
        TEST_ASSERT_GREATER_THAN_UINT16(0, gamma12((uint8_t)i));
    }
}

// ── the CW/WW split holds colour temperature ──────────────────────────────
// Applying the curve per-leg instead of to the total would turn a 2.98:1 mix
// into 10.83:1, so the fixture would drift warm as it dimmed.

void test_white_mix_conserves_the_total(void) {
    for (int level = 1; level < 256; level += 7) {
        for (int cct = 0; cct < 256; cct += 5) {
            const WhiteMix w = white_mix_gamma((uint8_t)level, (uint8_t)cct);
            const uint32_t total = gamma12((uint8_t)level);
            const uint32_t sum   = (uint32_t)w.ww + w.cw;
            TEST_ASSERT_TRUE(sum <= total);
            TEST_ASSERT_TRUE(sum + 2 >= total);
        }
    }
}

void test_white_mix_holds_the_ratio(void) {
    for (int level = 1; level < 256; level += 7) {
        for (int cct = 1; cct < 255; cct += 5) {
            const WhiteMix w = white_mix_gamma((uint8_t)level, (uint8_t)cct);
            // ww/cw should equal (255-cct)/cct. Cross-multiplied to stay in
            // integers: each side truncates by less than 1 LSB, and the two
            // errors are weighted by cct and (255-cct), which sum to 255 --
            // so a bound of 255 here IS the "within 1 LSB" property.
            const int32_t lhs = (int32_t)w.ww * cct;
            const int32_t rhs = (int32_t)w.cw * (255 - cct);
            TEST_ASSERT_TRUE(labs((long)(lhs - rhs)) < 255);
        }
    }
}

void test_white_mix_endpoints_are_pure(void) {
    const WhiteMix warm = white_mix_gamma(255, 0);
    TEST_ASSERT_EQUAL_UINT16(4095, warm.ww);
    TEST_ASSERT_EQUAL_UINT16(0,    warm.cw);

    const WhiteMix cool = white_mix_gamma(255, 255);
    TEST_ASSERT_EQUAL_UINT16(0,    cool.ww);
    TEST_ASSERT_EQUAL_UINT16(4095, cool.cw);
}

void test_white_mix_is_dark_when_off(void) {
    const WhiteMix w = white_mix_gamma(0, 128);
    TEST_ASSERT_EQUAL_UINT16(0, w.ww);
    TEST_ASSERT_EQUAL_UINT16(0, w.cw);
}

// ── the ring keeps its colour while dimming ───────────────────────────────
// Guards against someone "simplifying" this into per-channel gamma later.

void test_scale_brightness_gamma_preserves_channel_ratios(void) {
    const CRGB source = {255, 169, 87};        // the warm_white() mix
    for (int b = 16; b < 256; b += 5) {
        const CRGB out = scale_brightness_gamma(source, (uint8_t)b);
        TEST_ASSERT_TRUE(labs((long)out.r * source.g - (long)out.g * source.r) < 255);
        TEST_ASSERT_TRUE(labs((long)out.g * source.b - (long)out.b * source.g) < 255);
    }
}

void test_scale_brightness_gamma_endpoints(void) {
    const CRGB source = {255, 169, 87};
    const CRGB full   = scale_brightness_gamma(source, 255);
    TEST_ASSERT_EQUAL_UINT8(254, full.r);      // scale8 maps 255 -> 254
    const CRGB dark   = scale_brightness_gamma(source, 0);
    TEST_ASSERT_EQUAL_UINT8(0, dark.r);
    TEST_ASSERT_EQUAL_UINT8(0, dark.g);
    TEST_ASSERT_EQUAL_UINT8(0, dark.b);
}

int main(int, char**) {
    UNITY_BEGIN();
    RUN_TEST(test_gamma8_matches_the_formula);
    RUN_TEST(test_gamma12_matches_the_formula);
    RUN_TEST(test_both_curves_are_monotonic);
    RUN_TEST(test_endpoints_are_exact);
    RUN_TEST(test_no_nonzero_brightness_goes_dark);
    RUN_TEST(test_white_mix_conserves_the_total);
    RUN_TEST(test_white_mix_holds_the_ratio);
    RUN_TEST(test_white_mix_endpoints_are_pure);
    RUN_TEST(test_white_mix_is_dark_when_off);
    RUN_TEST(test_scale_brightness_gamma_preserves_channel_ratios);
    RUN_TEST(test_scale_brightness_gamma_endpoints);
    return UNITY_END();
}
